front_practica_2/routes/route_familia.py
from flask import Blueprint, redirect, render_template, request, flash
import requests

router_familia = Blueprint('router_familia',__name__)

@router_familia.route('/')
def home():
    return render_template('index.html')

@router_familia.route('/familia/table')
def table_familia():
    response = requests.post('http://localhost:8080/api/familia/all')
    familias = response.json()['data']
    j = 1
    for familia in familias: 
        familia['numero'] = j
        j += 1
    return render_template('familia/table_familia.html',familias=familias)


@router_familia.route('/familia/save')
def save_familia():
    response = requests.get('http://localhost:8080/api/familia/cantones_and_nivelesSE')
    return render_template('familia/save_familia.html',enumeracion=response.json())

@router_familia.route('/familia/save/send', methods=['POST'])
def save_familia_send():
    headers = {'Content-Type':'application/json'}
    data = request.form.to_dict()
    response = requests.post('http://localhost:8080/api/familia/save',json=data,headers=headers)
    if response.status_code == 200:
        flash('Datos de la familia guardados exitosamente!',category='info')
        return redirect('/familia/table')
    else:
        flash('Algo ha salido mal al intentar guardar los datos',category='error')
        return redirect('/familia/table')
    


@router_familia.route('/familia/update/<int:id>')
def update_familia(id):
    headers = {"Content-Type":"application/json"}
    response = requests.post(f'http://localhost:8080/api/familia/get',json={"id":id},headers=headers)
    familia = response.json()['data']
    response = requests.get('http://localhost:8080/api/familia/cantones_and_nivelesSE')
    enums = response.json()
    return render_template('familia/update_familia.html',context={"familia": familia, "enums" : enums})

@router_familia.route('/familia/update/send',methods=['POST'])
def update_familia_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/familia/update',json=data,headers=headers)
    if response.status_code == 200:
        flash('Datos de Familia modificados con éxito',category='info')
        return redirect('/familia/table')
    else:
        flash('Ocurrió un error al intentar modificar los datos',category='error')
        return redirect('/familia/table')

@router_familia.route('/delete/familia/<int:id>')
def delete_familia(id):
    response = requests.post(f'http://localhost:8080/api/familia/get',json={'id':id})
    familia = response.json()['data']
    return render_template('familia/delete_familia.html',familia=familia)

@router_familia.route('/delete/familia/send',methods=['POST'])
def delete_familia_send():
    headers = {'Content-Type':'application/json'}
    json = request.form.to_dict()
    print(json)
    response = requests.post('http://localhost:8080/api/familia/delete',json=json,headers=headers)
    print(response)
    if response.status_code == 200:
        flash('Familia eliminada!',category='info')
        return redirect('/familia/table')
    else:
        flash('Algo sallió mal, no se eliminaron los datos',category='error')
        return redirect('/familia/table')

front_practica_2/routes/route_generador.py
from .route_familia import *

router_generador = Blueprint('router_generador',__name__)

@router_generador.route('/generador/table')
def table_generador():
    response = requests.post('http://localhost:8080/api/generador/all')
    generadores = response.json()['data']
    i = 1
    for generador in generadores:
        generador['numero'] = i
        i += 1 
    return render_template('generador/table_generador.html',generadores=generadores)


@router_generador.route('/generador/save')
def save_generador():
    return render_template('/generador/save_generador.html')
    
@router_generador.route('/generador/save/send',methods=['POST'])
def save_generador_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/generador/save/',json=data,headers=headers)
    if response.status_code == 200:
        flash('Datos del generador guardados exitosamente!',category='info')
    else:
        flash('Ocurrió un error al intentar guardar los datos',category='error')
    return redirect('/generador/table')

@router_generador.route('/generador/update/<int:id>')
def update_generador(id):
    json={'id':id}
    headers={'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/generador/get/',json=json,headers=headers)
    generador = response.json()['data']
    return render_template('generador/update_generador.html',generador=generador)

@router_generador.route('/generador/update/send',methods=['POST'])
def update_generador_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/generador/update',json=json,headers=headers)
    print(response)
    if response.status_code == 200:
        flash('Datos del generador actualizados exitosamente!',category='info')
    else:
        flash('Ocurrió un error al intentar actualizar los datos',category='error')
    return redirect('/generador/table')


@router_generador.route('/generador/delete/<int:id>')
def delete_generador(id):
    json = {'id':id}
    headers={'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/generador/get',json=json,headers=headers)
    generador = response.json()['data']
    return render_template('generador/delete_generador.html',generador=generador)

@router_generador.route('/generador/delete/send',methods=['POST'])
def delete_generador_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/generador/delete',json=json,headers=headers)
    print(response)
    if response.status_code == 200:
        flash('Datos del generador eliminados',category='info')
    else:
        flash('Ocurrió un error al intentar eliminar los datos',category='error')
    return redirect('/generador/table')

front_practica_2/routes/route_transaccion.py
from .route_familia import *

router_transaccion = Blueprint('router_transaccion',__name__)

@router_transaccion.route('/transaccion/table')
def table_transaccion():
    response = requests.post('http://localhost:8080/api/transaccion/all')
    transacciones = response.json()['data']
    i = 1
    for transaccion in transacciones:
        transaccion['numero'] = i
        headers = {'Content-Type':'application/json'}
        familia = requests.post('http://localhost:8080/api/familia/get',json={'id':transaccion['familiaId']},headers=headers).json()['data']
        transaccion['apellidosFamilia'] = familia['apellidosRepresentantes']
        generador = requests.post('http://localhost:8080/api/generador/get',json={'id':transaccion['generadorId']},headers=headers).json()['data']
        transaccion['generadorModelo'] = generador['modelo']
        i += 1
    return render_template('transaccion/table_transaccion.html',transacciones=transacciones)


@router_transaccion.route('/transaccion/save')
def save_transaccion():
    response = requests.post('http://localhost:8080/api/familia/all')
    familias = response.json()['data']
    response = requests.post('http://localhost:8080/api/generador/all')
    generadores = response.json()['data']
    context={
        'familias' : familias,
        'generadores' : generadores
    }
    return render_template('/transaccion/save_transaccion.html',context=context)
    
@router_transaccion.route('/transaccion/save/send',methods=['POST'])
def save_transaccion_send():
    data = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/transaccion/save/',json=data,headers=headers)
    if response.status_code == 200:
        flash('Datos de la transaccion guardados exitosamente!',category='info')
    else:
        flash('Ocurrió un error al intentar guardar los datos',category='error')
    return redirect('/transaccion/table')

@router_transaccion.route('/transaccion/update/<int:id>')
def update_transaccion(id):
    json={'id':id}
    headers={'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/transaccion/get/',json=json,headers=headers)
    transaccion = response.json()['data']
    response = requests.post('http://localhost:8080/api/generador/all')
    generadores = response.json()['data']
    response = requests.post('http://localhost:8080/api/familia/all')
    familias = response.json()['data']
    context = {'familias': familias, 'generadores': generadores}
    return render_template('transaccion/update_transaccion.html',transaccion=transaccion,context=context)

@router_transaccion.route('/transaccion/update/send',methods=['POST'])
def update_transaccion_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/transaccion/update',json=json,headers=headers)
    print(response)
    if response.status_code == 200:
        flash('Datos de la transaccion actualizados exitosamente!',category='info')
    else:
        flash('Ocurrió un error al intentar actualizar los datos',category='error')
    return redirect('/transaccion/table')


@router_transaccion.route('/transaccion/delete/<int:id>')
def delete_transaccion(id):
    json = {'id':id}
    headers={'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/transaccion/get',json=json,headers=headers)
    transaccion = response.json()['data']
    return render_template('transaccion/delete_transaccion.html',transaccion=transaccion)

@router_transaccion.route('/transaccion/delete/send',methods=['POST'])
def delete_transaccion_send():
    json = request.form.to_dict()
    headers = {'Content-Type':'application/json'}
    response = requests.post('http://localhost:8080/api/transaccion/delete',json=json,headers=headers)
    print(response)
    if response.status_code == 200:
        flash('Datos de la transaccion eliminados',category='info')
    else:
        flash('Ocurrió un error al intentar eliminar los datos',category='error')
    return redirect('/transaccion/table')

front_practica_2/templates/base.html
<!DOCTYPE html>
<html class="loading" lang="es" data-textdirection="ltr">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
  <meta name="description"
    content="Chameleon Admin is a modern Bootstrap 4 webapp &amp; admin dashboard html template with a large number of components, elegant design, clean and organized code.">
  <meta name="keywords"
    content="admin template, Chameleon admin template, dashboard template, gradient admin template, responsive admin template, webapp, eCommerce dashboard, analytic dashboard">
  <meta name="author" content="ThemeSelect">
  <title>{% block title %}{% endblock %}</title>
  <link rel="apple-touch-icon" href="{{ url_for('static',filename='theme-assets/images/ico/apple-icon-120.png' ) }}">
  <link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static',filename='theme-assets/images/censo.png') }}">
  <link href="https://fonts.googleapis.com/css?family=Muli:300,300i,400,400i,600,600i,700,700i%7CComfortaa:300,400,700"
    rel="stylesheet">
  <link href="https://maxcdn.icons8.com/fonts/line-awesome/1.1/css/line-awesome.min.css" rel="stylesheet">
  <!-- BEGIN VENDOR CSS-->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='theme-assets/css/vendors.css') }}">
  <!-- END VENDOR CSS-->
  <!-- BEGIN CHAMELEON  CSS-->
  <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='theme-assets/css/app-lite.css') }}">
  <!-- END CHAMELEON  CSS-->
  <!-- BEGIN Page Level CSS-->
  <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='theme-assets/css/core/menu/menu-types/vertical-menu.css') }}">
  <link rel="stylesheet" type="text/css"
    href="{{ url_for('static',filename='theme-assets/css/core/colors/palette-gradient.css') }}">
  <!-- END Page Level CSS-->
  <!-- BEGIN Custom CSS-->
  <!-- END Custom CSS-->
</head>

<body class="vertical-layout vertical-menu 2-columns   menu-expanded fixed-navbar" data-open="click"
  data-menu="vertical-menu" data-color="bg-gradient-x-purple-blue" data-col="2-columns">

  <!-- fixed-top-->
  <nav
    class="header-navbar navbar-expand-md navbar navbar-with-menu navbar-without-dd-arrow fixed-top navbar-semi-light">
    <div class="navbar-wrapper">
      <div class="navbar-container content">
        <div class="collapse navbar-collapse show" id="navbar-mobile">
          <ul class="nav navbar-nav mr-auto float-left">
            <li class="nav-item d-block d-md-none"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                  class="ft-menu"></i></a></li>
            <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i
                  class="ficon ft-maximize"></i></a></li>
            <li class="nav-item dropdown navbar-search"><a class="nav-link dropdown-toggle hide" data-toggle="dropdown"
                href="#"><i class="ficon ft-search"></i></a>
              <ul class="dropdown-menu">
                <li class="arrow_box">
                  <form>
                    <div class="input-group search-box">
                      <div class="position-relative has-icon-right full-width">
                        <input class="form-control" id="search" type="text" placeholder="Search here...">
                        <div class="form-control-position navbar-search-close"><i class="ft-x"> </i></div>
                      </div>
                    </div>
                  </form>
                </li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav float-right">
            <li class="dropdown dropdown-language nav-item"><a class="dropdown-toggle nav-link" id="dropdown-flag"
                href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i
                  class="flag-icon flag-icon-us"></i><span class="selected-language"></span></a>
              <div class="dropdown-menu" aria-labelledby="dropdown-flag">
                <div class="arrow_box"><a class="dropdown-item" href="#"><i class="flag-icon flag-icon-us"></i>
                    English</a><a class="dropdown-item" href="#"><i class="flag-icon flag-icon-cn"></i> Chinese</a><a
                    class="dropdown-item" href="#"><i class="flag-icon flag-icon-ru"></i> Russian</a><a
                    class="dropdown-item" href="#"><i class="flag-icon flag-icon-fr"></i> French</a><a
                    class="dropdown-item" href="#"><i class="flag-icon flag-icon-es"></i> Spanish</a></div>
              </div>
            </li>
          </ul>
          <ul class="nav navbar-nav float-right">
            <li class="dropdown dropdown-notification nav-item"><a class="nav-link nav-link-label" href="#"
                data-toggle="dropdown"><i class="ficon ft-mail"> </i></a>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="arrow_box_right"><a class="dropdown-item" href="#"><i class="ft-book"></i> Read Mail</a><a
                    class="dropdown-item" href="#"><i class="ft-bookmark"></i> Read Later</a><a class="dropdown-item"
                    href="#"><i class="ft-check-square"></i> Mark all Read </a></div>
              </div>
            </li>
            <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link" href="#"
                data-toggle="dropdown"> <span class="avatar avatar-online"><img
                    src="{{ url_for('static',filename='theme-assets/images/portrait/small/avatar-s-19.png') }}"
                    alt="avatar"><i></i></span></a>
              <div class="dropdown-menu dropdown-menu-right">
                <div class="arrow_box_right"><a class="dropdown-item" href="#"><span class="avatar avatar-online"><img
                        src="{{ url_for('static',filename='theme-assets/images/portrait/small/avatar-s-19.png') }}"
                        alt="avatar"><span class="user-name text-bold-700 ml-1">John Doe</span></span></a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="#"><i class="ft-user"></i> Edit
                    Profile</a><a class="dropdown-item" href="#"><i class="ft-mail"></i> My Inbox</a><a
                    class="dropdown-item" href="#"><i class="ft-check-square"></i> Task</a><a class="dropdown-item"
                    href="#"><i class="ft-message-square"></i> Chats</a>
                  <div class="dropdown-divider"></div><a class="dropdown-item" href="#"><i class="ft-power"></i>
                    Logout</a>
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>

  <!-- ////////////////////////////////////////////////////////////////////////////-->


  <div class="main-menu menu-fixed menu-light menu-accordion    menu-shadow " data-scroll-to-active="true"
    data-img="{{ url_for('static',filename='theme-assets/images/backgrounds/02.jpg') }}">
    <div class="navbar-header">
      <ul class="nav navbar-nav flex-row">
        <li class="nav-item mr-auto"><a class="navbar-brand" href="/"><img class="brand-logo" alt="Chameleon admin logo"
              src="{{ url_for('static',filename='theme-assets/images/censo.png') }}" />
            <h3 class="brand-text">Censos Loja</h3>
          </a></li>
        <li class="nav-item d-md-none"><a class="nav-link close-navbar"><i class="ft-x"></i></a></li>
      </ul>
    </div>
  {% block main_menu_content %}
    
  {% endblock %}


  {% block app_content %}
    
  {% endblock %}

      <div class="content-body">
        <main>
         

          {% block content %}
            
          {% endblock %}

        </main>
      </div>
    </div>
  </div>
  <!-- ////////////////////////////////////////////////////////////////////////////-->


  <footer class="footer footer-static footer-light navbar-border navbar-shadow">
    <div class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span
        class="float-md-left d-block d-md-inline-block">2018 &copy; Copyright <a class="text-bold-800 grey darken-2"
          href="https://themeselection.com" target="_blank">ThemeSelection</a></span>
      <ul class="list-inline float-md-right d-block d-md-inline-blockd-none d-lg-block mb-0">
        <li class="list-inline-item"><a class="my-1" href="https://themeselection.com/" target="_blank"> More themes</a>
        </li>
        <li class="list-inline-item"><a class="my-1" href="https://themeselection.com/support" target="_blank">
            Support</a></li>
        <li class="list-inline-item"><a class="my-1"
            href="https://themeselection.com/products/chameleon-admin-modern-bootstrap-webapp-dashboard-html-template-ui-kit/"
            target="_blank"> Purchase</a></li>
      </ul>
    </div>
  </footer>

  <!-- BEGIN VENDOR JS-->
  <script src="{{ url_for('static',filename='theme-assets/vendors/js/vendors.min.js') }}"
    type="text/javascript"></script>
  <!-- BEGIN VENDOR JS-->
  <!-- BEGIN PAGE VENDOR JS-->
  <script src="{{ url_for('static',filename='theme-assets/vendors/js/charts/chart.min.js') }}"
    type="text/javascript"></script>
  <!-- END PAGE VENDOR JS-->
  <!-- BEGIN CHAMELEON  JS-->
  <script src="{{ url_for('static',filename='theme-assets/js/core/app-menu-lite.js') }}"
    type="text/javascript"></script>
  <script src="{{ url_for('static',filename='theme-assets/js/core/app-lite.js') }}" type="text/javascript"></script>
  <!-- END CHAMELEON  JS-->
  <!-- BEGIN PAGE LEVEL JS-->
  <script src="{{ url_for('static',filename='theme-assets/js/scripts/charts/chartjs/bar/column.js') }}"
    type="text/javascript"></script>
  <script src="{{ url_for('static',filename='theme-assets/js/scripts/charts/chartjs/bar/bar.js') }}"
    type="text/javascript"></script>
  <script src="{{ url_for('static',filename='theme-assets/js/scripts/charts/chartjs/line/line.js') }}"
    type="text/javascript"></script>
  <script src="{{ url_for('static',filename='theme-assets/js/scripts/charts/chartjs/pie-doughnut/pie-simple.js') }}"
    type="text/javascript"></script>
  <script
    src="{{ url_for('static',filename='theme-assets/js/scripts/charts/chartjs/pie-doughnut/doughnut-simple.js') }}"
    type="text/javascript"></script>
  <!-- END PAGE LEVEL JS-->
</body>

</html>

front_practica_2/templates/index.html
{% extends 'base.html' %}
{% block title %}Censos Loja{% endblock %}

{% block main_menu_content %}
<div class="main-menu-content">
  <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
    <li class="active"><a href="/"><i class="ft-home"></i><span class="menu-title"
          data-i18n="">Inicio</span></a>
    </li>
    <li class="nav-item"><a href="/familia/table"><i class="la la-group"></i><span class="menu-title"
          data-i18n="">Familias</span></a>
    </li>
    <li class="nav-item"><a href="/generador/table"><i class="la la-lightbulb-o"></i><span class="menu-title"
      data-i18n="">Generadores</span></a>
    </li>
    <li class="nav-item"><a href="/transaccion/table"><i class="la la-exchange"></i><span class="menu-title"
      data-i18n="">Transacciones</span></a>
    </li>
  </ul>
</div>
<div class="navigation-background"></div>
</div> 
{% endblock %}


{% block app_content %}
<div class="app-content content">
  <div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="content-header row">
      <div class="content-header-left col-md-4 col-12 mb-2">
        <h3 class="content-header-title">INICIO</h3>
      </div>
      <div class="content-header-right col-md-8 col-12">
        <div class="breadcrumbs-top float-md-right">
          <div class="breadcrumb-wrapper mr-1">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="/">Home</a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
      <h2 class="card-title">Sistema de Estadísticas y Censos: Censos Loja</h2>
  </div>
  <div class="card-block">
      <div class="card-body">
        <p>En esta aplicación usted podrá visualizar y modificar datos relevantes sobre la adquisición de generadores de energía eléctrica por parte de las familias lojanas.</p>
        <div class="card-block">
          <div class="card-header">
            <h4 class="card-title">Acciones Rápidas</h4>
          </div> 
          <div class="card-body">
            <div class="form-group">
              <a href="{{ url_for('router_familia.save_familia') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Familia</button>
              </a>
              <a href="{{ url_for('router_generador.save_generador') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Generador</button>
              </a>
              <a href="{{ url_for('router_transaccion.save_transaccion') }}">
                <button type="button" class="btn btn-primary btn-min-width mr-1 mb-1"><i class="la la-plus"></i> Agregar Transacción</button>
              </a>
            </div> 
          </div>          
        </div>        
      </div>
  </div>
</div>

<div class="col-12 mt-3 mb-1">
  <h4 class="text-uppercase">Sobre el Sistema</h4>
  <p>A continuación se muestra una pequeña descripción de las funcionalidades del sistema.</p>
</div>

<div class="row match-height">
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Familias</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/lLPJ0wjw3uvZW02pkZS9orsrrXCS-zSgcLoQl_wA2s0/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90by1ncmF0aXMv/ZmFtaWxpYS1mZWxp/ei1zZW50YWRvLXNv/ZmEtc2FsYS1lc3Rh/cl8yMy0yMTQ4NDU2/Mjc5LmpwZz9zZW10/PWFpc19oeWJyaWQ" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la lista actual de los datos de las familias registradas en el sistema</p>
        <a href="/familia/table" class="card-link">Ir a la sección</a>
      </div>
      <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Generadores</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/ufYnpi89XMW6nhfLAQNVG__DP2fTpewjbKgZ3I5n9II/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9odHRw/Mi5tbHN0YXRpYy5j/b20vRF9OUV9OUF82/NTQ0NTItTUxNNDA5/Nzc2Nzc3NjNfMDMy/MDIwLUYtZ2VuZXJh/ZG9yLWVsZWN0cmlj/by1hLWdhc29saW5h/LTU1MDAtdy1wcmV0/dWwtMjYwMzUud2Vi/cA" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la tabla con los datos de los generadores registrados en el sistema</p>
        <a href="/generador/table" class="card-link">Ir a la sección</a>
      </div>
      <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
      </div>
    </div>
  </div>
  <div class="col-lg-4 col-md-12">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Apartado de Transacciones</h4>
        <h6 class="card-subtitle text-muted">Tabla de datos con posibilidad de modificación</h6>
      </div>
      <img class="" src="https://imgs.search.brave.com/QRxPUjR_b0ySmDAoO-BVINxzd9465CwPtiw_4aTbdLo/rs:fit:860:0:0:0/g:ce/aHR0cHM6Ly9pbWcu/ZnJlZXBpay5jb20v/Zm90by1ncmF0aXMv/Z2VudGUtbmVnb2Np/b3MtZGFuZG9zZS1t/YW5vLWFjdWVyZG9f/NTM4NzYtMTE5Nzk2/LmpwZz9zaXplPTYy/NiZleHQ9anBn" alt="Card image cap">
      <div class="card-body">
        <p class="card-text">En esta sección usted podrá visualizar la lista actual de los datos de las transacciones registradas en el sistema</p>
        <a href="/transaccion/table" class="card-link">Ir a la sección</a>
        <div class="card-footer border-top-blue-grey border-top-lighten-5 text-muted">
        </div>
      </div>
    </div>
  </div>
</div>
  
{% endblock %}